# Generated by Django 3.2.8 on 2021-11-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glry', '0002_auto_20211129_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glry.location'),
        ),
    ]
