# Generated by Django 3.2.8 on 2021-11-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glry', '0004_auto_20211130_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='gallery_category',
        ),
        migrations.AddField(
            model_name='photos',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glry.location'),
        ),
    ]
